# Generated by Django 5.2.1 on 2025-06-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tileset",
            options={"verbose_name": "Tile Set", "verbose_name_plural": "Tile Sets"},
        ),
        migrations.AlterUniqueTogether(
            name="tileset",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tileset",
            name="variant",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("SpringWheat", "SpringWheat"),
                    ("WinterWheat", "WinterWheat"),
                ],
                default="",
                help_text="Wheat인 경우 SpringWheat 또는 WinterWheat, 그 외는 빈 문자열",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tileset",
            name="area",
            field=models.FloatField(
                blank=True, help_text="해당 variant의 면적 (m²)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tileset",
            name="crop_season",
            field=models.ForeignKey(
                help_text="참조 대상 (작물·연도·주)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tilesets",
                to="core.cropseason",
            ),
        ),
        migrations.AlterField(
            model_name="tileset",
            name="folder_path_cached",
            field=models.TextField(
                blank=True, help_text="MEDIA_ROOT 기준 캐싱된 폴더 경로"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tileset",
            unique_together={("crop_season", "variant")},
        ),
    ]
