# Generated by Django 5.2.8 on 2026-01-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('model_weights_path', models.CharField(max_length=512)),
                ('shapefile_path', models.CharField(blank=True, max_length=512)),
                ('batch_size', models.PositiveIntegerField(default=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_path', models.JSONField()),
                ('selected_states', models.JSONField(default=list)),
                ('target_crops', models.CharField(max_length=256)),
                ('output_dir_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pipelineconfig')),
            ],
        ),
    ]
