# Generated by Django 5.2.8 on 2026-01-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='celery_chain_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='celery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='celery_last_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
