# Generated by Django 5.2.8 on 2026-01-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_celery_chain_id_job_celery_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='JobOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('inference_tiles', 'Inference Tiles'), ('merged_cropmasks', 'Merged Cropmasks'), ('calculate_area', 'Calculate Area')], max_length=64)),
                ('relative_path', models.CharField(max_length=512)),
                ('absolute_path', models.CharField(max_length=1024)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('file_modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.job')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'step'], name='core_jobout_job_id_54c4d4_idx')],
                'unique_together': {('job', 'absolute_path')},
            },
        ),
    ]
