# Generated by Django 5.2.8 on 2026-01-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_crop_pipelineconfigcrop_pipelineconfig_crops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfig',
            name='model_weights_path',
            field=models.CharField(help_text='Absolute or relative path to model weights (not derived from input root).', max_length=512),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='shapefile_path',
            field=models.CharField(blank=True, help_text='Absolute or relative path to shapefile (not derived from input root).', max_length=512),
        ),
    ]
