# Generated by Django 5.2.8 on 2026-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inputroot_outputroot_delete_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputroot',
            name='path',
            field=models.CharField(help_text='Absolute or project-relative path for input root directory.', max_length=512),
        ),
        migrations.AlterField(
            model_name='outputroot',
            name='path',
            field=models.CharField(help_text='Absolute or project-relative path for output root directory.', max_length=512),
        ),
    ]
