# Generated by Django 5.2.8 on 2026-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_inputroot_path_alter_outputroot_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('weights', 'Weights'), ('shp', 'Shapefile')], max_length=16)),
                ('path', models.CharField(help_text='Absolute or project-relative path for root directory.', max_length=512)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InputRoot',
        ),
        migrations.DeleteModel(
            name='OutputRoot',
        ),
    ]
