# Generated by Django 5.2.8 on 2026-01-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rootpath_delete_inputroot_delete_outputroot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfig',
            name='model_weights_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='shapefile_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
