# Generated by Django 6.0.1 on 2026-01-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skip_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='skip_inference',
            field=models.BooleanField(default=False),
        ),
    ]
