# Generated by Django 6.0.1 on 2026-01-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_job_skip_area_job_skip_inference'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skip_merge',
            field=models.BooleanField(default=False),
        ),
    ]
