# Generated by Django 6.0.1 on 2026-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_job_skip_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="current_step",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
