# Generated by Django 6.0.1 on 2026-01-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_job_current_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpath",
            name="path_type",
            field=models.CharField(
                choices=[
                    ("input", "Input"),
                    ("output", "Output"),
                    ("weights", "Weights"),
                    ("shp", "Shapefile"),
                    ("logs", "Logs"),
                ],
                max_length=16,
            ),
        ),
    ]
