# Generated by Django 6.0.1 on 2026-01-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_rootpath_path_type"),
        ("core", "0016_job_gpu_count"),
    ]

    operations = []
