# Generated by Django 6.0.1 on 2026-01-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_merge_20260116_2354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="gpu_count",
            field=models.IntegerField(
                default=0, help_text="Number of GPUs to use. -1 for all, 0 for CPU."
            ),
        ),
    ]
