# Generated by Django 6.0.1 on 2026-01-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_job_gpu_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="gpu_count",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of GPUs to use. -1 for all, 0 for CPU.",
                null=True,
            ),
        ),
    ]
