# Generated by Django 6.0.1 on 2026-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_job_gpu_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboutput",
            name="bounds",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="joboutput",
            name="step",
            field=models.CharField(
                choices=[
                    ("inference_tiles", "Inference Tiles"),
                    ("merged_cropmasks", "Merged Cropmasks"),
                    ("calculate_area", "Calculate Area"),
                    ("mask_thumbnails", "Mask Thumbnails"),
                ],
                max_length=64,
            ),
        ),
    ]
