# Generated by Django 5.2.1 on 2025-06-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TileSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.FloatField(blank=True, null=True)),
                ("folder_path_cached", models.TextField(blank=True)),
                (
                    "crop_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tilesets",
                        to="core.cropseason",
                    ),
                ),
            ],
            options={
                "unique_together": {("crop_season",)},
            },
        ),
    ]
