# Generated by Django 5.2.1 on 2025-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(
                choices=[
                    ("Wheat", "Wheat"),
                    ("Wheat_Spring", "Wheat Spring"),
                    ("Wheat_Winter", "Wheat Winter"),
                    ("Soybean", "Soybean"),
                    ("Corn", "Corn"),
                ],
                max_length=50,
            ),
        ),
    ]
