# Generated by Django 5.1.8 on 2025-04-11 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("wheat", "Wheat"),
                            ("corn", "Corn"),
                            ("bean", "Bean"),
                        ],
                        default="wheat",
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("kansas", "Kansas"),
                            ("idaho", "Idaho"),
                            ("texas", "Texas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("progress", models.FloatField(default=0.0)),
                (
                    "tif_file",
                    models.FileField(blank=True, null=True, upload_to="jobs/%Y/%m/%d/"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
