# Generated by Django 5.1.8 on 2025-04-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="crop_type",
            field=models.CharField(
                choices=[("Wheat", "Wheat"), ("Corn", "Corn"), ("Bean", "Bean")],
                default="wheat",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="region",
            field=models.CharField(
                choices=[
                    ("Washington", "Washington"),
                    ("Oregon", "Oregon"),
                    ("Idaho", "Idaho"),
                    ("Texas", "Texas"),
                ],
                max_length=20,
            ),
        ),
    ]
