# Generated by Django 5.1.8 on 2025-04-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_crop_type_alter_job_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="region",
            field=models.CharField(
                choices=[
                    ("Washington", "Washington"),
                    ("Oregon", "Oregon"),
                    ("Idaho", "Idaho"),
                    ("Texas", "Texas"),
                    ("Kansas", "Kansas"),
                    ("Oklahoma", "Oklahoma"),
                    ("Colorado", "Colorado"),
                    ("Nebraska", "Nebraska"),
                ],
                max_length=20,
            ),
        ),
    ]
