# Generated by Django 5.2.1 on 2025-06-02 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_state_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variable",
                    models.CharField(
                        choices=[
                            ("pr", "Precipitation"),
                            ("tmmx", "Maximum Temperature"),
                            ("tmmn", "Minimum Temperature"),
                            ("srad", "Surface Radiation"),
                            ("vpd", "Vapor Pressure Deficit"),
                            ("rmin", "Minimum Relative Humidity"),
                            ("rmax", "Maximum Relative Humidity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("csv_path_cached", models.TextField(blank=True)),
                (
                    "crop_season",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cropseason",
                    ),
                ),
            ],
        ),
    ]
