# Generated by Django 5.2.1 on 2025-06-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0001_initial"),
        ("core", "0002_alter_state_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatedata",
            name="variable",
            field=models.CharField(
                choices=[
                    ("pr", "Precipitation"),
                    ("tmmx", "Maximum Temperature"),
                    ("tmmn", "Minimum Temperature"),
                    ("srad", "Surface Radiation"),
                    ("rmin", "Minimum Relative Humidity"),
                    ("rmax", "Maximum Relative Humidity"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="climatedata",
            unique_together={("crop_season", "variable")},
        ),
    ]
