# Generated by Django 5.2.1 on 2025-06-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0002_alter_climatedata_variable_and_more"),
        ("core", "0002_alter_state_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatedata",
            name="crop_season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.cropseason"
            ),
        ),
    ]
