# Generated by Django 5.1.8 on 2025-04-15 13:34

import tileupload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedtif",
            name="file",
            field=models.FileField(upload_to=tileupload.models.upload_path),
        ),
    ]
