# Generated by Django 5.1.8 on 2025-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tileupload", "0002_alter_uploadedtif_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedtif",
            name="color_labels_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
